@startuml projet

question "1" <-- "2" choice : is the answer of

choice "1..n" <-- "1" healthBar : is influenced by

player "1" <-- "3" healthBar : animate

game "1" <-- "1" player : plays in

game "0..n" <-- "0..n" question : is asked in

question "1" <-- "0..n" forumMessage : answer to

forumMessage "1" <-- "1" player : post

forumMessage "1" <-- "1" forumMessage : respond to

class question {
    - question: string
    - picture: string
}

class choice {
    - label: string
}

class player {
    - name: string
}

class healthBar {
    - name: string
    - maxValue: int
    - currentValue: int
}

class game {
    - daysCount: number 
}

class forumMessage {
    - title: string
    - message: string
}


@enduml