@startuml projet

question "1" <-- "2" choice : is the answer of

player "1" <-- "3" healthBar : animate

class question {
    - question: string
    - picture: string
}

class choice {
    - label: string
}

class player {

}

class healthBar {
    - name: string
    - maxValue: int
    - currentValue: int
}


@enduml